version: 0.2

phases:
  install:
    commands:
      - echo Setting up stuff...
      - python -m pip install --upgrade pip
      - python -V
  pre_build:
    commands:
      - cd cloudformation-custom-resources/os-customizer-lambda
      - pip install --target ./package -r requirements.txt
  build:
    commands:
      - zip -r ../../os-customizer-lambda.zip package/ src/
  post_build:
    commands:
artifacts:
  files:
    - os-customizer-lambda.zip

