version: 0.2

phases:
  install:
    commands:
      - echo Setting up stuff...
      - python -m pip install --upgrade pip
      - python -V
  pre_build:
    commands:
      - echo Preparing os-customizer-lambda
      - cd cloudformation-custom-resources/os-customizer-lambda
      - pip install --target ./package -r requirements.txt
#      - echo Preparing os-cognito-auth-lambda
#      - cd ../os-cognito-auth-lambda
#      - pwd
#      - pip install --target ./package -r requirements.txt
#      - echo Preparing domain-setter-lambda
#      - cd ../domain-setter-lambda
#      - pwd
#      - pip install --target ./package -r requirements.txt
  build:
    commands:
      - cp -R src/helpers/ package/
      - mkdir package/src
      - mkdir package/dashboards_definitions_json
      - cp -R src/dashboards_definitions_json/ package/src/dashboards_definitions_json
      - cp -R src/lambda_function.py package/
      - cd package
      - zip -r ../../../os-customizer-lambda.zip .
#      - zip -r ../../os-customizer-lambda.zip src/dashboards_definitions_json
#      - zip -r ../../os-customizer-lambda.zip src/helpers
#      - zip -r ../../os-customizer-lambda.zip src/lambda_function.py
#      - cd ../os-cognito-auth-lambda
#      - zip -r ../../os-cognito-auth-lambda.zip package/ src/
#      - cd ../domain-setter-lambda
#      - zip -r ../../domain-setter-lambda.zip package/ src/
  post_build:
    commands:
artifacts:
  files:
    - os-customizer-lambda.zip
    - os-cognito-auth-lambda.zip
    - domain-setter-lambda.zip

