version: 0.2

phases:
  install:
    commands:
      - echo Setting up stuff...
      - cd cloudformation-custom-resources/os-cognito-auth-lambda
      - ls -lah
  pre_build:
    commands:
  build:
    commands:
  post_build:
    commands:
artifacts:
  files:
#    - HelloWorld.jar

