version: 0.2

phases:
  install:
    commands:
      - echo Setting up stuff...
      - python -m pip install --upgrade pip
      - python -V
  pre_build:
    commands:
      - echo Preparing os-customizer-lambda
      - cd cloudformation-custom-resources/os-customizer-lambda
      - pip install --target ./package -r requirements.txt
      - echo Preparing os-cognito-auth-lambda
      - cd ../os-cognito-auth-lambda
      - pwd
      - pip install --target ./package -r requirements.txt
      - echo Preparing domain-setter-lambda
      - cd ../domain-setter-lambda
      - pwd
      - pip install --target ./package -r requirements.txt
  build:
    commands:
      - zip -r ../../os-customizer-lambda.zip package/ src/
      - cd ../os-cognito-auth-lambda
      - zip -r ../../os-cognito-auth-lambda.zip package/ src/
      - cd ../domain-setter-lambda
      - zip -r ../../domain-setter-lambda.zip package/ src/
  post_build:
    commands:
artifacts:
  files:
    - os-customizer-lambda.zip
    - os-cognito-auth-lambda
    - domain-setter-lambda

